Remove unused variable set_count
gfx_xconvert_bitmap() has a variable set_count which is incremented, but
never used. This is now causing a build failure:

chainloader/gfx/gfx.c: In function ‘gfx_convert_bitmap’:
chainloader/gfx/gfx.c:330:12: error: variable ‘set_count’ set but not used [-Werror=unused-but-set-variable=]
  330 |     UINT32 set_count = 0;
      |            ^~~~~~~~~
cc1: all warnings being treated as errors

Remove the variable.